### ISSUE TITLE
conversion of probe x sample matrix

### ISSUE THREAD

**Issue by joshuamschmidt** [cauwerx/CNV_GWAS_continuous_traits#1]
Thanks for providing this code repo from your excellent paper @cauwerx. 
I've tried to search within the repo, but it seems that scripts for the conversion of the probe x sample matrices are not included here? Is it possible to include them here?

Thanks

**Comment by cauwerx** [comment]
Dear Joshua,

Thank you for your interest in our work and apologies fo the delayed answer - I have been on holidays for the last couple of weeks.

Unfortunately, the original script was lost and this is the reason it is missing from the repo. In attachment, you’ll find a script that details the different steps to transform QS matrices into PLINK file sets using a simulated QS matrix of smaller size. As explained in the script, I advice to work on batch-level QS matrices and only merge all files corresponding to the same chromosome at the very end, before generating the PLINK file sets. My experience is that loading smaller chunks of data facilitates the processing.

I tried to annotate the script as well as possible but do not hesitate to reach out if you have any remaining questions.

Best,
Chiara

**Comment by joshuamschmidt** [comment]
Thanks Chiara for taking the time to provide example code for this.

Best regards,

Josh
